config/routes.rb
Rails.application.routes.draw do
	get 'posts', to: 'posts#index'
	post 'posts', to: 'posts#create'

	get 'posts/new'

	get 'posts/:id', to: 'posts#show', as: 'post'

	get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post' 

	patch 'posts/:id', to: 'posts#update'

	delete 'posts/:id', to: 'posts#destroy', as: 'destroy_post'

	


	root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@posts = Post.new
	end

	def create
		#asignacion individual
		# titulo = params[:post][:title]
		# contenido = params[:post][:content]
		#asignacion masiva(metodo priado)
		post = Post.new(post_params)
		if post.save
			redirect_to post, notice: "Se creo con exito"
		else
			redirect_to posts_new_path, notice: "no se pudo crear el post"
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post, notice: 'El post se a actualizado con exito'
		else
			redirect_to edit_post_path(@post.id), notice: 'no se a podido actualizar el registro'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path, notice: 'Se a eliminado el registro con exito'
	end

	private
	def post_params
		#asignacion masiva//strong params 
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudDesdeCero</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editando un Post</h1>

<%=form_with(model: @post, local: true) do |form| %>
	<%=form.label :title %>
	<%=form.text_field :title %>
	<br>
	<%=form.label :content %>
	<%=form.text_area :content %>
	<br>
	<%=form.submit 'Editar' %>
	<br>

	<%= link_to 'volver a index', root_path %>
<% end %>

app/views/posts/index.html.erb
<h5>
	<%= notice %>
</h5>


<h1>Index</h1>


<table>
	<tr>
		<th>Titulo</th>
		<th>Contenido</th>
	</tr>
	<% @posts.each do |post| %>
	<tr>
		<td><%= link_to post.title, post_path(post.id) %></td>
		<td><%= post.content %></td>
		<td><%= link_to 'Editar', edit_post_path(post) %></td>
		<td><%= link_to 'Eliminar', destroy_post_path(post), method: :delete %></td>
	</tr>
	<% end %>
</table>

<br>
<%= link_to 'crear nuevo post', posts_new_path %>

app/views/posts/new.html.erb
<%=form_with(model: @posts, local: true) do |form| %>
	<%=form.label :title %>
	<%=form.text_field :title %>
	<br>
	<%=form.label :content %>
	<%=form.text_area :content %>
	<br>
	<%=form.submit 'Crear' %>
	<br>
	<%= link_to 'volver a index', root_path %>
<% end %>

app/views/posts/show.html.erb
<h3>Detalle del post</h3>

<p>
<strong>Titulo:</strong> <%=@post.title %>
</p>
<p>
<strong>Contenido:</strong> <%=@post.content %>
</p>
<%= link_to 'editar', edit_post_path(@post) %>

<%= link_to 'Index', root_path %> 